preproc:
  SLIDING_WINDOW_SIZE : 3
training:
  bc:
    N_EPOCHS : 3500
    PATIENCE : 1000
    BATCH_SIZE : 1024
    WEIGHT_DECAY : 0
    LEARNING_RATE : 0.0003
    DROPOUT_RATE : 0.5
  oc:
    N_EPOCHS : 6000
    NUM_CLASSES : 5
    PATIENCE : 1000
    BATCH_SIZE : 1024
    WEIGHT_DECAY : 0
    LEARNING_RATE : 0.000003
    DROPOUT_RATE : 0.5
